// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYdDxbVuHLF3443ylkKcdKUDi2OXQbTaQ',
    appId: '1:420711547024:web:aa6be807575e7b88c99815',
    messagingSenderId: '420711547024',
    projectId: 'semproject-10fbe',
    authDomain: 'semproject-10fbe.firebaseapp.com',
    storageBucket: 'semproject-10fbe.firebasestorage.app',
    measurementId: 'G-CDVZ9XQJ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1RDv_YbjezH07WUJpRdz_apPeSSe6GQ',
    appId: '1:420711547024:android:1c46da8642ae72c7c99815',
    messagingSenderId: '420711547024',
    projectId: 'semproject-10fbe',
    storageBucket: 'semproject-10fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_4yPz9lO-RLyeHqd1Yd4DFz6-TivkAA',
    appId: '1:420711547024:ios:0038f7f8e86fec1ac99815',
    messagingSenderId: '420711547024',
    projectId: 'semproject-10fbe',
    storageBucket: 'semproject-10fbe.firebasestorage.app',
    iosBundleId: 'com.example.semProject',
  );

}